version: 0.2

phases:
  build:
    commands:
      - npm install
  post_build:
      commands:
        - mkdir build-output
        - mkdir -p build-output/node_modules
        - cp -R *.js build-output
        - cp -R node_modules/* build-output/node_modules
artifacts:
  type: zip
  files:
    - 'build-output/index.js'
    - 'build-output/node_modules/*'
