version: 0.2

phases:
  build:
    commands:
      - npm install
  post_build:
      commands:
        - mkdir build-output
        - cp -R index.js node_modules/ build-output
        - cd build-output/
        - zip -qr build-output.zip ./*
        - mv build-output.zip ../
artifacts:
  files:
    - build-output.zip