version: 0.2
phases:
  install:
    commands:
      - npm install
      - aws cloudformation package --template-file template.yaml --s3-bucket code-builds-artifacts --output-template-file cfn-transformed-output-template.yaml
artifacts:
  files:
    - template.yaml
    - cfn-transformed-output-template.yaml
