Resources:
  DDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: "certification-questions"
      AttributeDefinitions:
        -
          AttributeName: "QuestionId"
          AttributeType: "S"         
      KeySchema:
        -
          AttributeName: "QuestionId"
          KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5