AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: 'AWS Certification Quiz Lambda'
Resources:
  AWSCertification:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: aws-certification-quiz
      Role: arn:aws:iam::726095363876:role/lambda_access_dynamo_db
      CodeUri: .
      Handler: index.handler
      Runtime: 'nodejs8.10'
      AutoPublishAlias: live
      DeploymentPreference:
        Type: Linear10PercentEvery1Minute

  ServerLessCustomMetricFilter:
    Type: 'AWS::Logs::MetricFilter'
    Properties:
      LogGroupName: /aws/lambda/aws-certification-quiz
      FilterPattern: 'Correct answer'
      MetricTransformations:
        - MetricValue: 1
          MetricNamespace: CustomMetric
          MetricName: correct-answer-metric